// ── NEW MULTIPLE-CHOICE QUESTIONS (installment 1 of several toward 100/cell) ──
// Each question: { q, options:[4 strings], correctIndex (0-3), f: short fact shown after answering }.
// This sits ALONGSIDE the existing triviaQuestions.js — nothing in that file was
// touched or needs to change. The two get merged together inside App.js.
export const NEW_QUESTIONS = {
  tech: {
    easy: [
      {"q": "What does \"CPU\" stand for?", "options": ["Central Processing Unit", "Computer Power Unit", "Core Processing Utility", "Central Program Unit"], "correctIndex": 0, "f": "The CPU is often called the \"brain\" of a computer."},
      {"q": "Which company created the iPhone?", "options": ["Apple", "Samsung", "Google", "Microsoft"], "correctIndex": 0, "f": "The first iPhone was released in 2007."},
      {"q": "What does \"Wi-Fi\" let devices do?", "options": ["Connect to the internet wirelessly", "Charge wirelessly", "Print documents", "Cool down faster"], "correctIndex": 0, "f": "Wi-Fi uses radio waves to transmit data."},
      {"q": "What is the most-used search engine in the world?", "options": ["Google", "Bing", "Yahoo", "DuckDuckGo"], "correctIndex": 0, "f": "Google handles the large majority of global web searches."},
      {"q": "What does \"www\" stand for?", "options": ["World Wide Web", "World Web Wide", "Wide World Web", "Web World Wide"], "correctIndex": 0, "f": "It was coined by Tim Berners-Lee, who invented the web."},
      {"q": "Which of these is a social media platform?", "options": ["Instagram", "Photoshop", "Excel", "Windows"], "correctIndex": 0, "f": "Instagram was launched in 2010 and later bought by Facebook."},
    ],
    medium: [
      {"q": "Who co-founded Microsoft alongside Bill Gates?", "options": ["Paul Allen", "Steve Jobs", "Larry Page", "Jeff Bezos"], "correctIndex": 0, "f": "Paul Allen and Bill Gates founded Microsoft in 1975."},
      {"q": "What does \"HTML\" stand for?", "options": ["HyperText Markup Language", "High Text Modern Language", "Hyper Transfer Markup Logic", "HyperText Modern Link"], "correctIndex": 0, "f": "HTML is the standard language for building web pages."},
      {"q": "Which company owns YouTube?", "options": ["Google", "Meta", "Amazon", "Apple"], "correctIndex": 0, "f": "Google acquired YouTube in 2006."},
      {"q": "What does \"USB\" stand for?", "options": ["Universal Serial Bus", "United Serial Bus", "Universal System Bus", "Unified Serial Board"], "correctIndex": 0, "f": "USB was designed to standardize connections between devices."},
      {"q": "Which programming language is known for powering most websites' interactivity?", "options": ["JavaScript", "Python", "C++", "Swift"], "correctIndex": 0, "f": "JavaScript runs directly in web browsers."},
      {"q": "What is the name of Elon Musk's rocket company?", "options": ["SpaceX", "Blue Origin", "Virgin Galactic", "Starlink"], "correctIndex": 0, "f": "SpaceX was founded in 2002 and later became the first private company to send astronauts to orbit."},
    ],
    hard: [
      {"q": "In what year was the first iPhone released?", "options": ["2007", "2005", "2009", "2010"], "correctIndex": 0, "f": "Steve Jobs unveiled it at Macworld in January 2007."},
      {"q": "What does \"RAM\" stand for?", "options": ["Random Access Memory", "Rapid Access Memory", "Read Access Module", "Random Allocation Memory"], "correctIndex": 0, "f": "RAM temporarily stores data a computer is actively using."},
      {"q": "Who is credited as the inventor of the World Wide Web?", "options": ["Tim Berners-Lee", "Alan Turing", "Steve Wozniak", "Vint Cerf"], "correctIndex": 0, "f": "He proposed it in 1989 while working at CERN."},
      {"q": "Which company originally developed the Android operating system before Google acquired it?", "options": ["Android Inc.", "Nokia", "Motorola", "Palm"], "correctIndex": 0, "f": "Google bought Android Inc. in 2005."},
      {"q": "What does \"API\" stand for?", "options": ["Application Programming Interface", "Advanced Programming Interface", "Application Process Integration", "Automated Programming Instruction"], "correctIndex": 0, "f": "APIs let different software systems communicate with each other."},
      {"q": "Which company developed the first widely-used web browser, Mosaic?", "options": ["NCSA", "Microsoft", "Netscape", "IBM"], "correctIndex": 0, "f": "Mosaic was released in 1993 by the National Center for Supercomputing Applications."},
    ],
  },
  med: {
    easy: [
      {"q": "How many chambers does the human heart have?", "options": ["4", "2", "3", "6"], "correctIndex": 0, "f": "The heart has two atria and two ventricles."},
      {"q": "Which organ is responsible for pumping blood?", "options": ["Heart", "Liver", "Lungs", "Kidneys"], "correctIndex": 0, "f": "The heart beats roughly 100,000 times a day."},
      {"q": "What is the largest organ in the human body?", "options": ["Skin", "Liver", "Brain", "Lungs"], "correctIndex": 0, "f": "Skin makes up about 16% of total body weight."},
      {"q": "Which blood type is known as the \"universal donor\"?", "options": ["O negative", "AB positive", "A positive", "B negative"], "correctIndex": 0, "f": "O negative blood lacks the antigens that can trigger immune reactions."},
      {"q": "What is the normal human body temperature, roughly?", "options": ["37°C (98.6°F)", "40°C (104°F)", "34°C (93°F)", "39°C (102°F)"], "correctIndex": 0, "f": "Body temperature can naturally vary slightly through the day."},
      {"q": "Which part of the body is affected by asthma?", "options": ["Lungs", "Heart", "Kidneys", "Stomach"], "correctIndex": 0, "f": "Asthma causes the airways to narrow and swell."},
    ],
    medium: [
      {"q": "What is the medical term for high blood pressure?", "options": ["Hypertension", "Hypotension", "Hyperglycemia", "Tachycardia"], "correctIndex": 0, "f": "Hypertension is a major risk factor for heart disease and stroke."},
      {"q": "Which vitamin is primarily produced when skin is exposed to sunlight?", "options": ["Vitamin D", "Vitamin C", "Vitamin A", "Vitamin B12"], "correctIndex": 0, "f": "Vitamin D helps the body absorb calcium."},
      {"q": "What does \"MRI\" stand for?", "options": ["Magnetic Resonance Imaging", "Medical Radiation Imaging", "Mechanical Resonance Index", "Magnetic Radiology Instrument"], "correctIndex": 0, "f": "MRI uses magnetic fields rather than radiation to create images."},
      {"q": "Which gland regulates metabolism by producing hormones in the neck?", "options": ["Thyroid", "Pancreas", "Adrenal", "Pituitary"], "correctIndex": 0, "f": "The thyroid produces hormones that affect nearly every cell in the body."},
      {"q": "What is the name for a doctor who specializes in skin conditions?", "options": ["Dermatologist", "Cardiologist", "Neurologist", "Podiatrist"], "correctIndex": 0, "f": "Dermatology covers skin, hair, and nail conditions."},
      {"q": "Which disease is caused by a deficiency of insulin or insulin resistance?", "options": ["Diabetes", "Anemia", "Arthritis", "Asthma"], "correctIndex": 0, "f": "Diabetes affects how the body processes blood sugar."},
    ],
    hard: [
      {"q": "What is the function of red blood cells?", "options": ["Carry oxygen throughout the body", "Fight infection", "Clot blood", "Produce hormones"], "correctIndex": 0, "f": "Red blood cells contain hemoglobin, which binds to oxygen."},
      {"q": "Which organ produces insulin?", "options": ["Pancreas", "Liver", "Kidney", "Spleen"], "correctIndex": 0, "f": "The pancreas also produces digestive enzymes."},
      {"q": "What is the medical term for a heart attack?", "options": ["Myocardial infarction", "Cardiac arrest", "Angina", "Arrhythmia"], "correctIndex": 0, "f": "It occurs when blood flow to part of the heart is blocked."},
      {"q": "Which bone is the longest in the human body?", "options": ["Femur", "Tibia", "Humerus", "Fibula"], "correctIndex": 0, "f": "The femur is the thigh bone."},
      {"q": "What is the function of white blood cells?", "options": ["Fight infection", "Carry oxygen", "Clot wounds", "Regulate temperature"], "correctIndex": 0, "f": "White blood cells are a core part of the immune system."},
      {"q": "Which part of the brain controls balance and coordination?", "options": ["Cerebellum", "Cerebrum", "Medulla", "Hypothalamus"], "correctIndex": 0, "f": "The cerebellum sits at the back of the brain, below the cerebrum."},
    ],
  },
  politics: {
    easy: [
      {"q": "What is the term length for a United States president, per term?", "options": ["4 years", "5 years", "6 years", "3 years"], "correctIndex": 0, "f": "A US president can serve a maximum of two terms."},
      {"q": "What do you call a country ruled by a king or queen?", "options": ["Monarchy", "Republic", "Democracy", "Oligarchy"], "correctIndex": 0, "f": "In most modern monarchies, the monarch's powers are largely ceremonial."},
      {"q": "What is the name of the United Nations' headquarters city?", "options": ["New York City", "Geneva", "Washington D.C.", "London"], "correctIndex": 0, "f": "The UN was founded in 1945 after World War II."},
      {"q": "What is a government with no official religion called?", "options": ["Secular", "Theocratic", "Federal", "Colonial"], "correctIndex": 0, "f": "Secular governments separate religious institutions from the state."},
      {"q": "What is the name for a system where power is shared between a central and regional governments?", "options": ["Federalism", "Communism", "Anarchism", "Absolutism"], "correctIndex": 0, "f": "The United States, Nigeria, and Germany are all federal systems."},
      {"q": "What is the right to vote called?", "options": ["Suffrage", "Sovereignty", "Citizenship", "Constituency"], "correctIndex": 0, "f": "Suffrage movements historically fought to expand voting rights."},
    ],
    medium: [
      {"q": "How many permanent members does the UN Security Council have?", "options": ["5", "10", "15", "7"], "correctIndex": 0, "f": "The five permanent members are the US, UK, France, Russia, and China."},
      {"q": "What is the lower house of the United States Congress called?", "options": ["House of Representatives", "Senate", "Parliament", "Cabinet"], "correctIndex": 0, "f": "Representatives are elected every two years."},
      {"q": "Which document begins with \"We the People\"?", "options": ["The US Constitution", "The Declaration of Independence", "The Magna Carta", "The Bill of Rights"], "correctIndex": 0, "f": "It was adopted in 1787."},
      {"q": "What is the term for an election to remove an official before their term ends?", "options": ["Recall election", "Referendum", "Primary", "Runoff"], "correctIndex": 0, "f": "Several US states allow recall elections for governors."},
      {"q": "What is the name of the UK's lower house of Parliament?", "options": ["House of Commons", "House of Lords", "Senate", "Privy Council"], "correctIndex": 0, "f": "Members of the House of Commons are elected by the public."},
      {"q": "What is a government made up of multiple political parties sharing power called?", "options": ["Coalition government", "Single-party state", "Federal republic", "Confederation"], "correctIndex": 0, "f": "Coalition governments are common in countries with proportional representation."},
    ],
    hard: [
      {"q": "How many senators represent each US state, regardless of population?", "options": ["2", "1", "3", "4"], "correctIndex": 0, "f": "This gives smaller states equal representation in the Senate."},
      {"q": "What is the term for the first ten amendments to the US Constitution?", "options": ["The Bill of Rights", "The Articles of Confederation", "The Federalist Papers", "The Preamble"], "correctIndex": 0, "f": "They were ratified in 1791."},
      {"q": "What is the minimum age to serve as a US Senator?", "options": ["30", "25", "35", "21"], "correctIndex": 0, "f": "US Representatives must be at least 25, while Senators must be at least 30."},
      {"q": "Which political ideology generally favors minimal government intervention in the economy?", "options": ["Libertarianism", "Communism", "Fascism", "Monarchism"], "correctIndex": 0, "f": "Libertarianism emphasizes individual liberty and limited state power."},
      {"q": "What is the practice of redrawing electoral district lines to favor a particular party called?", "options": ["Gerrymandering", "Filibustering", "Lobbying", "Canvassing"], "correctIndex": 0, "f": "The term dates back to Massachusetts Governor Elbridge Gerry in 1812."},
      {"q": "What is the name for a prolonged speech used to delay a legislative vote, especially in the US Senate?", "options": ["Filibuster", "Gerrymander", "Caucus", "Veto"], "correctIndex": 0, "f": "Ending a filibuster in the US Senate typically requires 60 votes."},
    ],
  },
  economics: {
    easy: [
      {"q": "What is the term for the general rise in prices over time?", "options": ["Inflation", "Deflation", "Recession", "Depression"], "correctIndex": 0, "f": "Inflation reduces how much a given amount of money can buy."},
      {"q": "What do you call money saved in a bank that earns extra money over time?", "options": ["Interest", "Tax", "Dividend", "Credit"], "correctIndex": 0, "f": "Interest rates vary between savings accounts and banks."},
      {"q": "What is a country's total economic output called?", "options": ["GDP", "CPI", "ROI", "APR"], "correctIndex": 0, "f": "GDP stands for Gross Domestic Product."},
      {"q": "What is the exchange of goods and services without using money called?", "options": ["Barter", "Trade deficit", "Inflation", "Subsidy"], "correctIndex": 0, "f": "Bartering was common before standardized currency existed."},
      {"q": "What is money borrowed that must be paid back called?", "options": ["A loan", "A grant", "A subsidy", "A dividend"], "correctIndex": 0, "f": "Loans usually come with interest charges."},
      {"q": "What do we call the amount of a good that consumers want at a given price?", "options": ["Demand", "Supply", "Surplus", "Deficit"], "correctIndex": 0, "f": "Demand tends to rise as prices fall, all else being equal."},
    ],
    medium: [
      {"q": "What is the term for a sustained decline in economic activity across an economy?", "options": ["Recession", "Inflation", "Appreciation", "Surplus"], "correctIndex": 0, "f": "A recession is commonly defined as two consecutive quarters of economic decline."},
      {"q": "What does \"GDP\" stand for?", "options": ["Gross Domestic Product", "General Domestic Price", "Gross Direct Profit", "Government Deficit Plan"], "correctIndex": 0, "f": "GDP measures the total value of goods and services produced in a country."},
      {"q": "What is a tax on imported goods called?", "options": ["Tariff", "Subsidy", "Levy", "Quota"], "correctIndex": 0, "f": "Tariffs can be used to protect domestic industries from foreign competition."},
      {"q": "Which organization sets interest rates in the United States?", "options": ["The Federal Reserve", "The World Bank", "The IMF", "The Treasury"], "correctIndex": 0, "f": "The Federal Reserve is the US central bank."},
      {"q": "What is the term for when a currency loses value relative to others?", "options": ["Depreciation", "Appreciation", "Inflation", "Deflation"], "correctIndex": 0, "f": "Depreciation can make a country's exports cheaper for foreign buyers."},
      {"q": "What is a monopoly?", "options": ["A single seller dominating a market", "A government subsidy", "A type of tax", "A trade agreement"], "correctIndex": 0, "f": "Monopolies can limit competition and raise prices for consumers."},
    ],
    hard: [
      {"q": "Which economist is considered the father of modern economics, author of \"The Wealth of Nations\"?", "options": ["Adam Smith", "John Maynard Keynes", "Karl Marx", "Milton Friedman"], "correctIndex": 0, "f": "Adam Smith's work was published in 1776."},
      {"q": "What is the term for the minimum wage a government sets by law?", "options": ["Minimum wage", "Living wage", "Base salary", "Wage floor index"], "correctIndex": 0, "f": "Minimum wage laws vary significantly across countries and regions."},
      {"q": "What does \"CPI\" measure?", "options": ["Changes in the price of a basket of consumer goods", "Company profit margins", "Currency exchange rates", "National debt levels"], "correctIndex": 0, "f": "CPI stands for Consumer Price Index and is a common inflation measure."},
      {"q": "What is the term for when a government spends more than it collects in revenue?", "options": ["Budget deficit", "Trade surplus", "Fiscal surplus", "Capital gain"], "correctIndex": 0, "f": "Governments often borrow money to cover budget deficits."},
      {"q": "Which economic theory argues that government spending can help pull an economy out of a recession?", "options": ["Keynesian economics", "Supply-side economics", "Austrian economics", "Monetarism"], "correctIndex": 0, "f": "It's named after economist John Maynard Keynes."},
      {"q": "What is the term for a market structure with only a few large sellers?", "options": ["Oligopoly", "Monopoly", "Monopsony", "Perfect competition"], "correctIndex": 0, "f": "Airlines and telecom companies are common real-world examples."},
    ],
  },
  social: {
    easy: [
      {"q": "What is a common greeting gesture in many cultures?", "options": ["Handshake", "High five", "Bow", "Hug"], "correctIndex": 0, "f": "Handshakes are believed to have originated as a sign of peaceful intent."},
      {"q": "What do you call a gathering of friends to celebrate an occasion?", "options": ["A party", "A meeting", "A conference", "A seminar"], "correctIndex": 0, "f": "Parties can mark birthdays, holidays, or achievements."},
      {"q": "What is the term for a person you've just met for the first time?", "options": ["A stranger", "A relative", "A colleague", "A mentor"], "correctIndex": 0, "f": "First impressions often form within seconds of meeting someone."},
      {"q": "What do most cultures consider polite when entering someone's home?", "options": ["Greeting the host", "Ignoring everyone", "Taking food first", "Leaving immediately"], "correctIndex": 0, "f": "Greeting customs vary, but acknowledging the host is nearly universal."},
      {"q": "What is a close group of friends often called?", "options": ["A circle", "A squad", "A network", "A team"], "correctIndex": 0, "f": "The phrase \"inner circle\" refers to someone's closest confidants."},
      {"q": "What is the act of listening closely and responding thoughtfully called?", "options": ["Active listening", "Passive hearing", "Multitasking", "Interrupting"], "correctIndex": 0, "f": "Active listening is considered a key relationship-building skill."},
    ],
    medium: [
      {"q": "What term describes the discomfort felt when returning to a familiar place after being away?", "options": ["Reverse culture shock", "Jet lag", "Homesickness", "Nostalgia"], "correctIndex": 0, "f": "It often catches people off guard more than the initial move abroad did."},
      {"q": "What is the sociological term for the unwritten rules guiding social behavior?", "options": ["Social norms", "Social capital", "Social mobility", "Social stratification"], "correctIndex": 0, "f": "Norms can vary widely between cultures and generations."},
      {"q": "What do we call a person's online representation of themselves?", "options": ["Digital persona", "Avatar handle", "Virtual identity", "Profile echo"], "correctIndex": 2, "f": "People often curate their virtual identity differently from daily life."},
      {"q": "What is the term for feeling anxious about missing out on experiences others are having?", "options": ["FOMO", "Imposter syndrome", "Burnout", "Social fatigue"], "correctIndex": 0, "f": "FOMO stands for \"fear of missing out.\""},
      {"q": "What is the term for a close bond formed between people through shared experiences?", "options": ["Camaraderie", "Hierarchy", "Etiquette", "Diplomacy"], "correctIndex": 0, "f": "Camaraderie is common among teammates, classmates, and coworkers."},
      {"q": "What is it called when people imitate the behavior of a larger group?", "options": ["Social conformity", "Social mobility", "Social gradient", "Social contract"], "correctIndex": 0, "f": "Conformity can be influenced by a desire to fit in or avoid conflict."},
    ],
    hard: [
      {"q": "What is the sociological term for the theory that people compare themselves to others to evaluate their own worth?", "options": ["Social comparison theory", "Social exchange theory", "Cognitive dissonance theory", "Attribution theory"], "correctIndex": 0, "f": "It was first proposed by psychologist Leon Festinger in 1954."},
      {"q": "What is \"Dunbar's number,\" the commonly cited limit on stable social relationships a person can maintain?", "options": ["About 150", "About 50", "About 500", "About 15"], "correctIndex": 0, "f": "It's named after anthropologist Robin Dunbar."},
      {"q": "What term describes a small, informal gathering of people with shared interests?", "options": ["A clique", "A caucus", "A cohort", "A syndicate"], "correctIndex": 0, "f": "Cliques are especially studied in the context of school social dynamics."},
      {"q": "What is the term for behaving differently depending on who is watching, a concept from sociologist Erving Goffman?", "options": ["Impression management", "Social facilitation", "Groupthink", "Cultural relativism"], "correctIndex": 0, "f": "Goffman compared social life to a theatrical performance."},
      {"q": "What is the term for a network of personal relationships that can provide practical or emotional support?", "options": ["Social capital", "Social gradient", "Social mobility", "Social contract"], "correctIndex": 0, "f": "The concept was popularized by sociologists like Pierre Bourdieu."},
      {"q": "What is \"groupthink\"?", "options": ["When a group prioritizes agreement over critical evaluation", "A brainstorming technique", "A type of peer review", "A leadership style"], "correctIndex": 0, "f": "The term was coined by psychologist Irving Janis in 1972."},
    ],
  },
  education: {
    easy: [
      {"q": "What is the first level of formal schooling usually called?", "options": ["Primary school", "University", "Graduate school", "Vocational school"], "correctIndex": 0, "f": "Primary school typically covers ages 5 to 11 in many countries."},
      {"q": "What do you call a person who teaches students?", "options": ["A teacher", "A principal", "A student", "A librarian"], "correctIndex": 0, "f": "Teachers often specialize in specific subjects at higher grade levels."},
      {"q": "What is a document earned after completing university studies called?", "options": ["A degree", "A badge", "A license", "A permit"], "correctIndex": 0, "f": "Degrees commonly include bachelor's, master's, and doctoral levels."},
      {"q": "What do students usually receive at the end of a course to show performance?", "options": ["A grade", "A trophy", "A salary", "A contract"], "correctIndex": 0, "f": "Grading systems vary widely between countries."},
      {"q": "What is the term for learning done outside a traditional classroom, over the internet?", "options": ["Online learning", "Homeschooling", "Tutoring", "Apprenticeship"], "correctIndex": 0, "f": "Online learning grew rapidly in popularity during the 2010s and 2020s."},
      {"q": "What is a school for young children before primary school called?", "options": ["Kindergarten", "College", "Academy", "Seminary"], "correctIndex": 0, "f": "The word \"kindergarten\" is German for \"children's garden.\""},
    ],
    medium: [
      {"q": "What is the term for a scholar who has earned the highest academic degree?", "options": ["A doctorate holder", "A dean", "A fellow", "A provost"], "correctIndex": 0, "f": "A doctorate is often abbreviated as a PhD."},
      {"q": "What is a curriculum?", "options": ["The subjects and content taught in a course of study", "A school's sports schedule", "A list of teachers", "A student's report card"], "correctIndex": 0, "f": "Curricula can vary significantly between schools and countries."},
      {"q": "What is the term for a test taken to measure what a student has learned?", "options": ["An assessment", "A syllabus", "A thesis", "A transcript"], "correctIndex": 0, "f": "Assessments can be formal exams or informal quizzes."},
      {"q": "What is the term for education focused on a specific trade or skill?", "options": ["Vocational education", "Liberal arts education", "Continuing education", "Remedial education"], "correctIndex": 0, "f": "Vocational training often leads directly to a specific career path."},
      {"q": "What is a \"gap year\"?", "options": ["A year off between stages of education, often for travel or work", "A failed academic year", "A year spent repeating a grade", "An extra year added to graduation requirements"], "correctIndex": 0, "f": "Gap years are especially common between high school and university."},
      {"q": "What is the term for a student studying at a university but not yet graduated?", "options": ["Undergraduate", "Postgraduate", "Alumnus", "Faculty"], "correctIndex": 0, "f": "Undergraduate programs typically lead to a bachelor's degree."},
    ],
    hard: [
      {"q": "What learning theory emphasizes that knowledge is built by learners through experience, associated with Jean Piaget?", "options": ["Constructivism", "Behaviorism", "Essentialism", "Perennialism"], "correctIndex": 0, "f": "Piaget studied how children's thinking develops in stages."},
      {"q": "What is the term for the gap in academic performance between different demographic groups?", "options": ["Achievement gap", "Learning curve", "Grade inflation", "Attrition rate"], "correctIndex": 0, "f": "It's widely studied in education policy research."},
      {"q": "What is \"Bloom's Taxonomy\" used to classify?", "options": ["Levels of learning objectives, from basic recall to creation", "Types of school buildings", "Categories of student misbehavior", "Grading scales"], "correctIndex": 0, "f": "It was developed by educational psychologist Benjamin Bloom in 1956."},
      {"q": "What is the term for a university's governing academic staff as a whole?", "options": ["Faculty", "Alumni", "Cohort", "Senate"], "correctIndex": 0, "f": "\"Faculty\" can also refer to a specific academic division, like a Faculty of Law."},
      {"q": "What is \"grade inflation\"?", "options": ["A gradual rise in average grades awarded over time, without a matching rise in achievement", "A policy that raises tuition yearly", "A system that ranks students nationally", "A method for calculating GPA"], "correctIndex": 0, "f": "It's a frequent topic of debate in higher education."},
      {"q": "What is the term for independent research required to earn a doctoral degree?", "options": ["A dissertation", "A syllabus", "A transcript", "An internship"], "correctIndex": 0, "f": "Dissertations are typically defended orally before a committee."},
    ],
  },
  entertainment: {
    easy: [
      {"q": "What is the term for a movie shown in theaters for the first time?", "options": ["A premiere", "A rerun", "A sequel", "A trailer"], "correctIndex": 0, "f": "Premieres are often attended by the cast and media."},
      {"q": "What streaming service is known for the show \"Stranger Things\"?", "options": ["Netflix", "Hulu", "Disney+", "Amazon Prime"], "correctIndex": 0, "f": "The show debuted in 2016."},
      {"q": "What do you call a short preview of an upcoming movie?", "options": ["A trailer", "A premiere", "A sequel", "A pilot"], "correctIndex": 0, "f": "Trailers are designed to build excitement before a film's release."},
      {"q": "What is the annual award show that honors achievements in film called?", "options": ["The Oscars", "The Grammys", "The Emmys", "The Tonys"], "correctIndex": 0, "f": "The Oscars are officially called the Academy Awards."},
      {"q": "What do you call the first episode of a new TV series?", "options": ["The pilot", "The finale", "The premiere", "The special"], "correctIndex": 0, "f": "Pilots are used to pitch a show idea to networks or studios."},
      {"q": "Which award show honors achievements in music?", "options": ["The Grammys", "The Oscars", "The Emmys", "The Tonys"], "correctIndex": 0, "f": "The Grammy Awards began in 1959."},
    ],
    medium: [
      {"q": "What award honors achievements in television?", "options": ["The Emmys", "The Oscars", "The Grammys", "The Tonys"], "correctIndex": 0, "f": "The Emmy statuette depicts a winged woman holding an atom."},
      {"q": "What is a movie that continues a story from an earlier film called?", "options": ["A sequel", "A prequel", "A reboot", "A spin-off"], "correctIndex": 0, "f": "A \"prequel,\" by contrast, tells a story that happens before the original."},
      {"q": "What is the term for a TV show spun off from a character in another show?", "options": ["A spin-off", "A reboot", "A remake", "An adaptation"], "correctIndex": 0, "f": "Spin-offs let popular side characters headline their own series."},
      {"q": "What award show honors achievements in Broadway theater?", "options": ["The Tonys", "The Oscars", "The Grammys", "The Emmys"], "correctIndex": 0, "f": "The Tony Awards are named after theater producer Antoinette Perry."},
      {"q": "What is it called when a studio remakes an old film or show with a new cast and updated style?", "options": ["A reboot", "A sequel", "A prequel", "A crossover"], "correctIndex": 0, "f": "Reboots often reimagine the original concept rather than directly continue its story."},
      {"q": "What is the term for a single season's worth of episodes released all at once for binge-watching?", "options": ["A season drop", "A premiere week", "A limited run", "A marathon release"], "correctIndex": 0, "f": "Netflix popularized this release model starting with House of Cards in 2013."},
    ],
    hard: [
      {"q": "Which film won the first-ever Academy Award for Best Picture, in 1929?", "options": ["Wings", "Casablanca", "Gone with the Wind", "It Happened One Night"], "correctIndex": 0, "f": "The award was presented at a ceremony that lasted just 15 minutes."},
      {"q": "What is the term for an actor who performs dangerous stunts in place of the main actor?", "options": ["A stunt double", "An understudy", "A body double", "An extra"], "correctIndex": 0, "f": "Stunt performers train extensively in specific physical disciplines."},
      {"q": "What is a \"cameo\" appearance?", "options": ["A brief appearance by a notable person, usually playing themselves or a minor role", "The opening scene of a film", "A character's final scene", "A post-credits scene"], "correctIndex": 0, "f": "Cameos are often used as a fun surprise for audiences."},
      {"q": "What term describes a film that blends two or more genres, like horror and comedy?", "options": ["A genre hybrid", "A crossover", "An anthology", "A mockumentary"], "correctIndex": 0, "f": "Genre-blending films can appeal to multiple types of audiences at once."},
      {"q": "What is the term for music composed specifically to accompany a film?", "options": ["A film score", "A soundtrack album", "A theme song", "A jingle"], "correctIndex": 0, "f": "A \"soundtrack\" more broadly can include licensed songs as well as the score."},
      {"q": "What is a \"box office bomb\"?", "options": ["A film that performs very poorly financially", "A film that wins a major award", "An unreleased film", "A film shown only overseas"], "correctIndex": 0, "f": "Box office success is typically measured against a film's production budget."},
    ],
  },
  history: {
    easy: [
      {"q": "In which year did World War II end?", "options": ["1945", "1939", "1950", "1918"], "correctIndex": 0, "f": "The war ended with Japan's surrender in September 1945."},
      {"q": "Who was the first President of the United States?", "options": ["George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"], "correctIndex": 0, "f": "Washington served two terms, from 1789 to 1797."},
      {"q": "Which ancient civilization built the pyramids at Giza?", "options": ["Ancient Egypt", "Ancient Rome", "Ancient Greece", "The Maya"], "correctIndex": 0, "f": "The Great Pyramid was built around 2560 BCE."},
      {"q": "What wall divided a European city from 1961 to 1989?", "options": ["The Berlin Wall", "The Great Wall of China", "Hadrian's Wall", "The Vienna Wall"], "correctIndex": 0, "f": "Its fall in 1989 symbolized the end of the Cold War era in Europe."},
      {"q": "Which ship famously sank in 1912 after hitting an iceberg?", "options": ["The Titanic", "The Lusitania", "The Mayflower", "The Bismarck"], "correctIndex": 0, "f": "Over 1,500 people died in the disaster."},
      {"q": "Who is credited with discovering the Americas for Europe in 1492?", "options": ["Christopher Columbus", "Ferdinand Magellan", "Marco Polo", "Vasco da Gama"], "correctIndex": 0, "f": "Columbus was seeking a westward route to Asia."},
    ],
    medium: [
      {"q": "Which empire was ruled by Julius Caesar?", "options": ["The Roman Empire", "The Ottoman Empire", "The Persian Empire", "The British Empire"], "correctIndex": 0, "f": "Caesar was assassinated in 44 BCE."},
      {"q": "What year did the French Revolution begin?", "options": ["1789", "1776", "1804", "1812"], "correctIndex": 0, "f": "It led to the end of the French monarchy."},
      {"q": "Which country was formerly known as Persia?", "options": ["Iran", "Iraq", "Turkey", "Egypt"], "correctIndex": 0, "f": "The name officially changed to Iran in 1935."},
      {"q": "Who wrote the \"I Have a Dream\" speech and delivered it in 1963?", "options": ["Martin Luther King Jr.", "Malcolm X", "Nelson Mandela", "Frederick Douglass"], "correctIndex": 0, "f": "It was delivered during the March on Washington."},
      {"q": "Which war was fought between the North and South regions of the United States from 1861 to 1865?", "options": ["The American Civil War", "The Revolutionary War", "World War I", "The War of 1812"], "correctIndex": 0, "f": "It ended with the abolition of slavery in the US."},
      {"q": "Which explorer led the first expedition to circumnavigate the globe, though he died before completing it?", "options": ["Ferdinand Magellan", "Christopher Columbus", "James Cook", "Vasco da Gama"], "correctIndex": 0, "f": "His crew completed the journey in 1522."},
    ],
    hard: [
      {"q": "In what year did the Berlin Wall fall?", "options": ["1989", "1991", "1985", "1993"], "correctIndex": 0, "f": "Germany was formally reunified less than a year later, in 1990."},
      {"q": "Which treaty formally ended World War I?", "options": ["The Treaty of Versailles", "The Treaty of Paris", "The Treaty of Rome", "The Treaty of Westphalia"], "correctIndex": 0, "f": "It was signed in 1919, imposing heavy terms on Germany."},
      {"q": "Who was the longest-reigning monarch in British history, reigning for over 70 years?", "options": ["Queen Elizabeth II", "Queen Victoria", "King George III", "King Henry VIII"], "correctIndex": 0, "f": "She reigned from 1952 until her death in 2022."},
      {"q": "Which ancient wonder of the world was located in Alexandria, Egypt?", "options": ["The Lighthouse of Alexandria", "The Hanging Gardens", "The Colossus of Rhodes", "The Temple of Artemis"], "correctIndex": 0, "f": "It was one of the Seven Wonders of the Ancient World."},
      {"q": "What was the name of the pandemic that killed an estimated 50 million people between 1918 and 1919?", "options": ["The Spanish Flu", "The Black Death", "The Asian Flu", "Cholera"], "correctIndex": 0, "f": "Despite the name, it likely did not originate in Spain."},
      {"q": "Which empire was the largest contiguous land empire in history, founded by Genghis Khan?", "options": ["The Mongol Empire", "The Roman Empire", "The Ottoman Empire", "The British Empire"], "correctIndex": 0, "f": "At its peak, it stretched from Eastern Europe to the Sea of Japan."},
    ],
  },
  sports: {
    easy: [
      {"q": "How many players are on a standard soccer team on the field at once?", "options": ["11", "10", "9", "12"], "correctIndex": 0, "f": "That includes one goalkeeper."},
      {"q": "In which sport would you perform a slam dunk?", "options": ["Basketball", "Volleyball", "Tennis", "Golf"], "correctIndex": 0, "f": "A slam dunk is scored by forcefully putting the ball through the hoop."},
      {"q": "How often are the Summer Olympic Games held?", "options": ["Every 4 years", "Every 2 years", "Every year", "Every 5 years"], "correctIndex": 0, "f": "The Winter Olympics are also held every 4 years, offset by 2 years."},
      {"q": "What sport is played at Wimbledon?", "options": ["Tennis", "Golf", "Cricket", "Rugby"], "correctIndex": 0, "f": "Wimbledon is the oldest tennis tournament in the world."},
      {"q": "How many points is a touchdown worth in American football?", "options": ["6", "3", "7", "10"], "correctIndex": 0, "f": "An extra point or two-point conversion can be added after."},
      {"q": "What is the maximum number of players allowed on a basketball court per team at one time?", "options": ["5", "6", "7", "4"], "correctIndex": 0, "f": "Teams also have substitutes on the bench."},
    ],
    medium: [
      {"q": "Which country has won the most FIFA World Cup titles?", "options": ["Brazil", "Germany", "Argentina", "Italy"], "correctIndex": 0, "f": "Brazil has won the tournament five times."},
      {"q": "In golf, what term describes completing a hole one stroke under par?", "options": ["A birdie", "An eagle", "A bogey", "A par"], "correctIndex": 0, "f": "Two strokes under par is called an \"eagle.\""},
      {"q": "How many Grand Slam tournaments are there in tennis each year?", "options": ["4", "3", "5", "6"], "correctIndex": 0, "f": "They are the Australian Open, French Open, Wimbledon, and US Open."},
      {"q": "What is the term for a boxing match ending when one fighter cannot continue?", "options": ["A knockout", "A decision", "A draw", "A disqualification"], "correctIndex": 0, "f": "A \"technical knockout\" happens when a referee stops the fight."},
      {"q": "In cricket, how many players are on a team?", "options": ["11", "10", "9", "12"], "correctIndex": 0, "f": "Cricket is especially popular in India, England, and Australia."},
      {"q": "What is the term for scoring three goals in a single soccer match by one player?", "options": ["A hat-trick", "A triple play", "A grand slam", "A perfect game"], "correctIndex": 0, "f": "The term originated in cricket before spreading to other sports."},
    ],
    hard: [
      {"q": "Which country hosted the first modern Olympic Games in 1896?", "options": ["Greece", "France", "United Kingdom", "Italy"], "correctIndex": 0, "f": "They were held in Athens, honoring the ancient Greek origins of the Games."},
      {"q": "Who holds the record for most Olympic gold medals of all time?", "options": ["Michael Phelps", "Usain Bolt", "Carl Lewis", "Larisa Latynina"], "correctIndex": 0, "f": "The American swimmer won 23 gold medals across his career."},
      {"q": "What is the maximum break score possible in a single frame of snooker?", "options": ["147", "155", "100", "180"], "correctIndex": 0, "f": "Achieving it requires potting all reds with blacks, then all colors."},
      {"q": "Which boxer was famously known as \"The Greatest\"?", "options": ["Muhammad Ali", "Mike Tyson", "Floyd Mayweather", "Joe Frazier"], "correctIndex": 0, "f": "He won Olympic gold in 1960 before turning professional."},
      {"q": "In Formula 1, what is the term for the fastest lap of a qualifying session that determines starting position?", "options": ["Pole position", "Grid slot", "Fast track", "Lead lap"], "correctIndex": 0, "f": "Starting from pole position gives a significant racing advantage."},
      {"q": "Which country has won the most Cricket World Cup titles?", "options": ["Australia", "India", "England", "West Indies"], "correctIndex": 0, "f": "Australia has won the tournament multiple times since the competition began in 1975."},
    ],
  },
  music: {
    easy: [
      {"q": "How many strings does a standard guitar have?", "options": ["6", "4", "8", "5"], "correctIndex": 0, "f": "Bass guitars typically have 4 strings instead."},
      {"q": "Which instrument has black and white keys?", "options": ["Piano", "Violin", "Trumpet", "Drums"], "correctIndex": 0, "f": "A standard piano has 88 keys."},
      {"q": "What do you call a group of singers performing together?", "options": ["A choir", "An orchestra", "A band", "A quartet"], "correctIndex": 0, "f": "Choirs are especially common in churches and schools."},
      {"q": "Which music streaming service is known for its green logo?", "options": ["Spotify", "Apple Music", "YouTube Music", "Tidal"], "correctIndex": 0, "f": "Spotify launched in 2008."},
      {"q": "What is the term for the speed at which a piece of music is played?", "options": ["Tempo", "Pitch", "Melody", "Harmony"], "correctIndex": 0, "f": "Tempo is often measured in beats per minute."},
      {"q": "Which instrument is known as the \"king of instruments\" due to its size and range?", "options": ["The organ", "The piano", "The cello", "The harp"], "correctIndex": 0, "f": "Large pipe organs can have thousands of individual pipes."},
    ],
    medium: [
      {"q": "Which artist is known as the \"King of Pop\"?", "options": ["Michael Jackson", "Elvis Presley", "Prince", "Stevie Wonder"], "correctIndex": 0, "f": "His album \"Thriller\" remains one of the best-selling albums of all time."},
      {"q": "What is the term for a musical piece written for a solo instrument with orchestral accompaniment?", "options": ["A concerto", "A symphony", "A sonata", "An overture"], "correctIndex": 0, "f": "Concertos typically highlight the technical skill of the soloist."},
      {"q": "Which genre of music originated in New Orleans in the early 20th century?", "options": ["Jazz", "Reggae", "Country", "Techno"], "correctIndex": 0, "f": "Jazz blends African and European musical traditions."},
      {"q": "What does \"a cappella\" mean?", "options": ["Singing without instrumental accompaniment", "Singing in a group of two", "A fast musical tempo", "A type of guitar solo"], "correctIndex": 0, "f": "The term is Italian for \"in the manner of the chapel.\""},
      {"q": "Which band is known for the album \"Abbey Road\"?", "options": ["The Beatles", "The Rolling Stones", "Pink Floyd", "Queen"], "correctIndex": 0, "f": "The album cover's street-crossing photo became one of music's most iconic images."},
      {"q": "What is the term for the main repeated section of a pop song, usually its most memorable part?", "options": ["The chorus", "The bridge", "The verse", "The outro"], "correctIndex": 0, "f": "The chorus typically carries the song's central hook."},
    ],
    hard: [
      {"q": "Who composed the famous Four Seasons violin concertos?", "options": ["Antonio Vivaldi", "Johann Sebastian Bach", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven"], "correctIndex": 0, "f": "Vivaldi composed them around 1720."},
      {"q": "Which composer continued to write music after becoming almost completely deaf?", "options": ["Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Frédéric Chopin"], "correctIndex": 0, "f": "His Ninth Symphony premiered after he had lost most of his hearing."},
      {"q": "What is the term for a piece of music written in memory of someone who has died?", "options": ["A requiem", "An aria", "A nocturne", "A fugue"], "correctIndex": 0, "f": "Mozart's unfinished Requiem is one of the most famous examples."},
      {"q": "Which music genre emerged from Jamaica in the late 1960s, closely associated with Bob Marley?", "options": ["Reggae", "Ska", "Calypso", "Dancehall"], "correctIndex": 0, "f": "Reggae grew out of earlier genres like ska and rocksteady."},
      {"q": "What is a \"fugue\" in music?", "options": ["A composition technique where a theme is repeated and layered across voices", "A fast dance rhythm", "A type of string instrument", "A musical key signature"], "correctIndex": 0, "f": "Johann Sebastian Bach is especially famous for his fugues."},
      {"q": "Which record label was Motown, famous for launching stars like Stevie Wonder and The Supremes, founded in which US city?", "options": ["Detroit", "Chicago", "Memphis", "New York"], "correctIndex": 0, "f": "Motown was founded by Berry Gordy in 1959."},
    ],
  },
  food: {
    easy: [
      {"q": "Which country is traditionally credited with inventing pizza as we know it?", "options": ["Italy", "France", "Greece", "Spain"], "correctIndex": 0, "f": "Modern pizza is especially associated with Naples."},
      {"q": "What grain is the main ingredient in sushi?", "options": ["Rice", "Wheat", "Corn", "Barley"], "correctIndex": 0, "f": "Sushi rice is seasoned with vinegar, sugar, and salt."},
      {"q": "Which fruit is known for \"keeping the doctor away\" in a popular saying?", "options": ["Apple", "Orange", "Banana", "Grape"], "correctIndex": 0, "f": "The full saying is \"An apple a day keeps the doctor away.\""},
      {"q": "What is the main ingredient in guacamole?", "options": ["Avocado", "Tomato", "Onion", "Lime"], "correctIndex": 0, "f": "Guacamole originated in Mexico."},
      {"q": "Which drink is made by fermenting grapes?", "options": ["Wine", "Beer", "Whiskey", "Cider"], "correctIndex": 0, "f": "Different grape varieties produce different styles of wine."},
      {"q": "What spice is derived from the Crocus flower and is the world's most expensive by weight?", "options": ["Saffron", "Cinnamon", "Nutmeg", "Vanilla"], "correctIndex": 0, "f": "It takes thousands of flowers to produce a single pound of saffron."},
    ],
    medium: [
      {"q": "Which country is the origin of the dish \"paella\"?", "options": ["Spain", "Portugal", "Mexico", "Italy"], "correctIndex": 0, "f": "Paella originated in the Valencia region."},
      {"q": "What is the main ingredient in traditional hummus?", "options": ["Chickpeas", "Lentils", "Black beans", "Peanuts"], "correctIndex": 0, "f": "Hummus is popular throughout the Middle East."},
      {"q": "Which country is credited with inventing the croissant?", "options": ["Austria", "France", "Belgium", "Switzerland"], "correctIndex": 0, "f": "The croissant was later popularized in France."},
      {"q": "What type of cuisine is \"kimchi\" from?", "options": ["Korean", "Japanese", "Chinese", "Thai"], "correctIndex": 0, "f": "Kimchi is traditionally made from fermented vegetables, often napa cabbage."},
      {"q": "Which spice gives curry its distinctive yellow color?", "options": ["Turmeric", "Paprika", "Cumin", "Coriander"], "correctIndex": 0, "f": "Turmeric is also studied for its potential health benefits."},
      {"q": "What is the term for food that is both vegetarian and contains no animal products at all, including dairy and eggs?", "options": ["Vegan", "Pescatarian", "Flexitarian", "Kosher"], "correctIndex": 0, "f": "Vegan diets exclude all animal-derived ingredients."},
    ],
    hard: [
      {"q": "Which country is the largest producer of coffee in the world?", "options": ["Brazil", "Colombia", "Vietnam", "Ethiopia"], "correctIndex": 0, "f": "Brazil has been the top coffee producer for over 150 years."},
      {"q": "What fermentation process is used to make traditional soy sauce?", "options": ["A mix of soybeans, wheat, and a fermenting mold culture", "Simple boiling of soybeans", "Distillation of fermented rice", "Pressing of raw soybeans"], "correctIndex": 0, "f": "Traditional soy sauce fermentation can take months."},
      {"q": "Which country is considered the birthplace of chocolate, where cacao was first cultivated?", "options": ["Mexico", "Switzerland", "Belgium", "Ghana"], "correctIndex": 0, "f": "The ancient Olmec and Maya civilizations used cacao in rituals and drinks."},
      {"q": "What is \"umami,\" one of the five basic tastes?", "options": ["A savory, meaty taste", "A bitter aftertaste", "A sour tang", "A spicy heat"], "correctIndex": 0, "f": "Umami is especially associated with ingredients like soy sauce and mushrooms."},
      {"q": "Which country is the origin of the fermented tea drink \"kombucha\"?", "options": ["China", "Japan", "India", "Russia"], "correctIndex": 0, "f": "Kombucha is made by fermenting sweetened tea with a bacteria-yeast culture."},
      {"q": "What is the name for the French cooking technique of slowly cooking food in its own fat?", "options": ["Confit", "Flambé", "Sauté", "Braise"], "correctIndex": 0, "f": "Duck confit is a classic example of this technique."},
    ],
  },
  humanrights: {
    easy: [
      {"q": "What document, adopted by the UN in 1948, outlines basic rights for all people?", "options": ["The Universal Declaration of Human Rights", "The Geneva Convention", "The UN Charter", "The Treaty of Versailles"], "correctIndex": 0, "f": "It was adopted on December 10, 1948, now marked as Human Rights Day."},
      {"q": "What is the right to express opinions freely called?", "options": ["Freedom of speech", "Freedom of movement", "Freedom of assembly", "Freedom of religion"], "correctIndex": 0, "f": "Many constitutions explicitly protect this right."},
      {"q": "What is the term for treating all people equally regardless of background?", "options": ["Equality", "Hierarchy", "Segregation", "Discrimination"], "correctIndex": 0, "f": "Equality is a core principle in most human rights frameworks."},
      {"q": "What is the right to practice any faith, or none at all, called?", "options": ["Freedom of religion", "Freedom of press", "Freedom of assembly", "Freedom of expression"], "correctIndex": 0, "f": "It's protected in many international human rights agreements."},
      {"q": "What is unfair treatment based on a trait like race or gender called?", "options": ["Discrimination", "Diplomacy", "Mediation", "Legislation"], "correctIndex": 0, "f": "Anti-discrimination laws exist in many countries worldwide."},
      {"q": "What is the right to a fair trial an example of?", "options": ["A legal right", "A privilege", "A courtesy", "A tradition"], "correctIndex": 0, "f": "Fair trial rights are foundational to most justice systems."},
    ],
    medium: [
      {"q": "Which organization is primarily responsible for promoting human rights globally through the United Nations?", "options": ["The UN Human Rights Council", "The International Monetary Fund", "The World Trade Organization", "The World Bank"], "correctIndex": 0, "f": "It was established in 2006, replacing an earlier UN commission."},
      {"q": "What is the term for forcing someone to work without pay or the ability to leave, a modern form of slavery?", "options": ["Forced labor", "Volunteering", "Internship", "Apprenticeship"], "correctIndex": 0, "f": "It remains a serious issue tracked by international organizations today."},
      {"q": "What right ensures people cannot be detained without being charged with a crime?", "options": ["The right to due process", "The right to assembly", "The right to privacy", "The right to property"], "correctIndex": 0, "f": "It's a cornerstone of legal systems that follow the rule of law."},
      {"q": "What is the term for people forced to flee their home country due to persecution or conflict?", "options": ["Refugees", "Immigrants", "Tourists", "Expatriates"], "correctIndex": 0, "f": "Refugee status is defined under international law, including the 1951 Refugee Convention."},
      {"q": "Which human rights treaty focuses specifically on protecting the rights of children?", "options": ["The Convention on the Rights of the Child", "The Geneva Convention", "The Universal Declaration of Human Rights", "The Treaty of Rome"], "correctIndex": 0, "f": "It was adopted by the UN in 1989 and is one of the most widely ratified treaties in history."},
      {"q": "What is the term for the right of workers to organize and negotiate collectively with employers?", "options": ["The right to unionize", "The right to strike alone", "The right to resign", "The right to overtime"], "correctIndex": 0, "f": "This right is protected in many labor laws around the world."},
    ],
    hard: [
      {"q": "In what year was the Universal Declaration of Human Rights adopted?", "options": ["1948", "1945", "1950", "1960"], "correctIndex": 0, "f": "It was adopted by the UN General Assembly in Paris."},
      {"q": "Which human rights concept refers to rights that cannot be taken away under any circumstances?", "options": ["Inalienable rights", "Conditional rights", "Derived rights", "Statutory rights"], "correctIndex": 0, "f": "The term appears prominently in historic documents like the US Declaration of Independence."},
      {"q": "What international court was established to prosecute individuals for genocide, war crimes, and crimes against humanity?", "options": ["The International Criminal Court", "The International Court of Justice", "The European Court of Human Rights", "The World Court of Trade"], "correctIndex": 0, "f": "It was established by the Rome Statute in 2002, based in The Hague."},
      {"q": "Which document is often considered an early precursor to modern human rights law, signed in England in 1215?", "options": ["The Magna Carta", "The Bill of Rights", "The Petition of Right", "The Act of Settlement"], "correctIndex": 0, "f": "It limited the power of the English monarchy and established certain legal protections."},
      {"q": "What term describes systemic policies that legally separated people by race, notably practiced in South Africa until the 1990s?", "options": ["Apartheid", "Segregation", "Colonialism", "Federalism"], "correctIndex": 0, "f": "Apartheid officially ended in South Africa in 1994."},
      {"q": "Which human rights principle holds that certain rights, like the prohibition of torture, can never be suspended, even during emergencies?", "options": ["Non-derogable rights", "Conditional rights", "Reciprocal rights", "Delegated rights"], "correctIndex": 0, "f": "These protections remain in force even during a declared state of emergency."},
    ],
  },
  geography: {
    easy: [
      {"q": "What is the largest continent by land area?", "options": ["Asia", "Africa", "North America", "Europe"], "correctIndex": 0, "f": "Asia covers about 30% of the world's total land area."},
      {"q": "Which river is the longest in the world?", "options": ["The Nile", "The Amazon", "The Yangtze", "The Mississippi"], "correctIndex": 0, "f": "The Nile flows through northeastern Africa."},
      {"q": "What is the capital city of France?", "options": ["Paris", "London", "Berlin", "Madrid"], "correctIndex": 0, "f": "Paris is also known as the \"City of Light.\""},
      {"q": "Which ocean is the largest in the world?", "options": ["The Pacific Ocean", "The Atlantic Ocean", "The Indian Ocean", "The Arctic Ocean"], "correctIndex": 0, "f": "The Pacific covers about a third of the Earth's surface."},
      {"q": "What is the smallest country in the world by land area?", "options": ["Vatican City", "Monaco", "San Marino", "Liechtenstein"], "correctIndex": 0, "f": "Vatican City is about 0.17 square miles."},
      {"q": "Which desert is the largest hot desert in the world?", "options": ["The Sahara", "The Gobi", "The Kalahari", "The Mojave"], "correctIndex": 0, "f": "The Sahara spans much of North Africa."},
    ],
    medium: [
      {"q": "Which mountain range contains Mount Everest, the tallest peak above sea level?", "options": ["The Himalayas", "The Andes", "The Alps", "The Rockies"], "correctIndex": 0, "f": "Mount Everest sits on the border of Nepal and Tibet."},
      {"q": "Which African country has the largest population?", "options": ["Nigeria", "Egypt", "Ethiopia", "South Africa"], "correctIndex": 0, "f": "Nigeria's population has grown rapidly over the past several decades."},
      {"q": "What is the largest country in the world by land area?", "options": ["Russia", "Canada", "China", "United States"], "correctIndex": 0, "f": "Russia spans eleven time zones."},
      {"q": "Which country has the most natural lakes in the world?", "options": ["Canada", "Finland", "Russia", "United States"], "correctIndex": 0, "f": "Canada contains a large share of the world's fresh water."},
      {"q": "Which strait separates Europe and Africa at its narrowest point?", "options": ["The Strait of Gibraltar", "The Bosphorus Strait", "The Strait of Hormuz", "The Bering Strait"], "correctIndex": 0, "f": "It connects the Atlantic Ocean to the Mediterranean Sea."},
      {"q": "What is the driest continent on Earth (excluding Antarctica's ice-covered interior)?", "options": ["Australia", "Africa", "Asia", "South America"], "correctIndex": 0, "f": "Much of Australia's interior is arid desert."},
    ],
    hard: [
      {"q": "Which country has the most time zones, even more than Russia?", "options": ["France", "United States", "Russia", "United Kingdom"], "correctIndex": 0, "f": "Thanks to its overseas territories, France spans 12 time zones."},
      {"q": "What is the name of the point where the Earth's rotational axis meets its surface in the north?", "options": ["The North Pole", "The Arctic Circle", "The Equator", "The Prime Meridian"], "correctIndex": 0, "f": "It sits in the middle of the Arctic Ocean, largely covered by sea ice."},
      {"q": "Which sea is so salty that people can easily float on its surface?", "options": ["The Dead Sea", "The Red Sea", "The Caspian Sea", "The Black Sea"], "correctIndex": 0, "f": "Its high salt content comes from having no outlet and high evaporation."},
      {"q": "Which line of latitude divides the Earth into the Northern and Southern Hemispheres?", "options": ["The Equator", "The Prime Meridian", "The Tropic of Cancer", "The Arctic Circle"], "correctIndex": 0, "f": "It sits at 0 degrees latitude."},
      {"q": "What is the name of the imaginary line at 0 degrees longitude, passing through Greenwich, England?", "options": ["The Prime Meridian", "The Equator", "The International Date Line", "The Tropic of Capricorn"], "correctIndex": 0, "f": "It's used as the reference point for Coordinated Universal Time (UTC)."},
      {"q": "Which landlocked sea is actually the world's largest inland body of water?", "options": ["The Caspian Sea", "The Dead Sea", "The Aral Sea", "Lake Victoria"], "correctIndex": 0, "f": "It borders countries including Russia, Kazakhstan, and Iran."},
    ],
  },
  popculture: {
    easy: [
      {"q": "What does a \"meme\" typically refer to online?", "options": ["A humorous image, video, or text shared widely", "A type of video call", "A private message", "A software update"], "correctIndex": 0, "f": "The term \"meme\" was originally coined by biologist Richard Dawkins in 1976."},
      {"q": "What is a short-form video app known for dance trends and lip-syncs, popular since 2018?", "options": ["TikTok", "LinkedIn", "Zoom", "Dropbox"], "correctIndex": 0, "f": "TikTok became one of the most downloaded apps in the world."},
      {"q": "What term describes a celebrity's devoted fans, often organized online?", "options": ["A fandom", "A syndicate", "A cohort", "A lobby"], "correctIndex": 0, "f": "Fandoms often create their own online communities and slang."},
      {"q": "What is the term for a video, image, or trend that spreads rapidly online?", "options": ["Viral content", "Trending topic", "Breaking news", "Sponsored content"], "correctIndex": 0, "f": "Content can go viral within hours on social platforms."},
      {"q": "What do you call someone who posts regularly on social media as a career?", "options": ["An influencer", "A broadcaster", "A journalist", "A publicist"], "correctIndex": 0, "f": "Influencer marketing has grown into a major advertising industry."},
      {"q": "What streaming platform is best known for live video game broadcasts?", "options": ["Twitch", "Netflix", "Hulu", "Spotify"], "correctIndex": 0, "f": "Twitch was acquired by Amazon in 2014."},
    ],
    medium: [
      {"q": "What term describes releasing an entire season of a show at once for viewers to watch quickly?", "options": ["Binge-release", "Season drop", "Marathon premiere", "Full unlock"], "correctIndex": 0, "f": "Netflix popularized this model, changing how people watch television."},
      {"q": "What is \"cancel culture\" generally used to describe?", "options": ["Public withdrawal of support from a person after controversial actions", "A trend of canceling streaming subscriptions", "A type of music genre", "A fashion movement"], "correctIndex": 0, "f": "The term became widely used in public discourse starting in the late 2010s."},
      {"q": "What is the term for content, especially images, edited or exaggerated for comedic effect online?", "options": ["A meme", "A vlog", "A podcast", "A livestream"], "correctIndex": 0, "f": "Memes often evolve rapidly, with new formats replacing old ones."},
      {"q": "What popular event, held annually, celebrates comic books, movies, and gaming fandoms, with major versions in San Diego and New York?", "options": ["Comic-Con", "Coachella", "Sundance", "E3"], "correctIndex": 0, "f": "San Diego Comic-Con has run since 1970."},
      {"q": "What does \"FOMO\" mean, a common term in internet culture?", "options": ["Fear of missing out", "Fun on my own", "Focus on me only", "Finish on move out"], "correctIndex": 0, "f": "It's often linked to heavy social media use."},
      {"q": "What term describes a brand or celebrity being \"exposed\" for hypocrisy or wrongdoing online?", "options": ["Being called out", "Being rebranded", "Being verified", "Being trending"], "correctIndex": 0, "f": "Call-out posts can spread quickly and generate major public attention."},
    ],
    hard: [
      {"q": "Which social media platform was originally called \"FaceMash\" before its rebrand?", "options": ["Facebook", "Instagram", "Twitter", "Snapchat"], "correctIndex": 0, "f": "It was created by Mark Zuckerberg while he was a student at Harvard."},
      {"q": "What year did the first iPhone's App Store launch, kickstarting the modern mobile app era?", "options": ["2008", "2007", "2010", "2005"], "correctIndex": 0, "f": "The App Store launched about a year after the original iPhone."},
      {"q": "What was the original name of the platform that later became known as X?", "options": ["Twitter", "Tumblr", "Vine", "Periscope"], "correctIndex": 0, "f": "The platform was rebranded following its acquisition by Elon Musk in 2022."},
      {"q": "What term describes the phenomenon of internet trends and jokes becoming outdated within days or weeks?", "options": ["Meme decay", "Trend fatigue", "Content churn", "Viral collapse"], "correctIndex": 0, "f": "The speed of internet culture has accelerated significantly with short-form video."},
      {"q": "Which video-sharing platform did Google acquire in 2006, just over a year after its launch?", "options": ["YouTube", "Vimeo", "Dailymotion", "Twitch"], "correctIndex": 0, "f": "The deal was valued at around $1.65 billion."},
      {"q": "What is the term for an account pretending to be someone else online, often for satire or deception?", "options": ["A parody or impersonation account", "A verified account", "A bot network", "An influencer handle"], "correctIndex": 0, "f": "Many platforms have specific policies distinguishing parody from impersonation."},
    ],
  },
  relationships: {
    easy: [
      {"q": "What is commonly considered a key ingredient for a healthy relationship?", "options": ["Trust", "Jealousy", "Distance", "Secrecy"], "correctIndex": 0, "f": "Trust is frequently cited by relationship researchers as foundational."},
      {"q": "What term describes the period early in a relationship marked by excitement and strong attraction?", "options": ["The honeymoon phase", "The cooling-off period", "The adjustment stage", "The trial phase"], "correctIndex": 0, "f": "This phase is often linked to a surge in certain brain chemicals."},
      {"q": "What is a common way couples show appreciation for each other?", "options": ["Acts of kindness", "Ignoring each other", "Avoiding conversation", "Criticism"], "correctIndex": 0, "f": "Small gestures are often cited as strengthening long-term bonds."},
      {"q": "What is it called when two people agree to spend their lives together through marriage?", "options": ["A union", "A contract", "A partnership deal", "An arrangement"], "correctIndex": 0, "f": "Marriage traditions vary widely across cultures."},
      {"q": "What is considered important for resolving disagreements in a relationship?", "options": ["Communication", "Avoidance", "Silence", "Competition"], "correctIndex": 0, "f": "Open communication is widely cited by therapists as key to conflict resolution."},
      {"q": "What term describes a friendship that has lasted many years?", "options": ["A longtime friendship", "A new acquaintance", "A rivalry", "A business contact"], "correctIndex": 0, "f": "Long friendships are often linked to greater life satisfaction in studies."},
    ],
    medium: [
      {"q": "What are the \"five love languages,\" a popular relationship framework, generally believed to describe?", "options": ["Different ways people express and receive love", "Stages of a breakup", "Types of family structures", "Phases of a first date"], "correctIndex": 0, "f": "The concept was introduced by author Gary Chapman in 1992."},
      {"q": "What term describes a relationship where both partners maintain a high level of independence alongside closeness?", "options": ["Interdependence", "Codependency", "Isolation", "Detachment"], "correctIndex": 0, "f": "Healthy interdependence is often distinguished from unhealthy codependency."},
      {"q": "What is \"attachment style\" in relationship psychology generally believed to be shaped by?", "options": ["Early childhood bonding experiences", "Astrological signs", "Blood type", "Birth order alone"], "correctIndex": 0, "f": "Attachment theory was developed by psychologist John Bowlby."},
      {"q": "What term describes maintaining a relationship primarily or entirely over long distances?", "options": ["A long-distance relationship", "A situationship", "An open relationship", "A rebound"], "correctIndex": 0, "f": "Long-distance relationships have become more common with video calling technology."},
      {"q": "What is \"active listening\" generally considered important for in relationships?", "options": ["Making your partner feel heard and understood", "Winning an argument", "Multitasking during conversations", "Changing the subject quickly"], "correctIndex": 0, "f": "It typically involves reflecting back what the other person said before responding."},
      {"q": "What term describes a gradual, often unspoken process of a relationship ending without a clear breakup conversation?", "options": ["Ghosting", "Dating", "Courting", "Rekindling"], "correctIndex": 0, "f": "The term became widely used alongside the rise of online dating."},
    ],
    hard: [
      {"q": "According to psychologist John Gottman's research, what is cited as one of the strongest predictors of divorce in a relationship?", "options": ["Contempt expressed during conflict", "Living in different cities", "Having different hobbies", "Marrying young"], "correctIndex": 0, "f": "Gottman identified contempt as part of what he called the \"Four Horsemen\" of relationship breakdown."},
      {"q": "What are the four attachment styles commonly described in attachment theory?", "options": ["Secure, anxious, avoidant, and disorganized", "Happy, sad, angry, and calm", "Dominant, passive, assertive, and neutral", "Romantic, platonic, familial, and professional"], "correctIndex": 0, "f": "Attachment style is thought to influence how people approach closeness and conflict in relationships."},
      {"q": "What term, coined more recently, describes an undefined romantic relationship without clear labels or commitment?", "options": ["A situationship", "A courtship", "A betrothal", "An engagement"], "correctIndex": 0, "f": "The term grew in popular use through social media and dating culture discussions."},
      {"q": "In relationship psychology, what is \"limerence\" generally used to describe?", "options": ["An intense, often involuntary state of infatuation", "A formal marriage proposal", "A type of couples therapy", "A stage of long-term commitment"], "correctIndex": 0, "f": "The term was coined by psychologist Dorothy Tennov in the 1970s."},
      {"q": "What does \"love bombing\" refer to in relationship psychology?", "options": ["Overwhelming someone with excessive affection and attention early on, sometimes as a manipulation tactic", "A surprise party for an anniversary", "A type of couples counseling exercise", "A wedding tradition"], "correctIndex": 0, "f": "It's a term often discussed in the context of unhealthy relationship patterns."},
      {"q": "What relationship structure involves more than two people consensually in a romantic relationship together?", "options": ["Polyamory", "Monogamy", "Courtship", "Betrothal"], "correctIndex": 0, "f": "Polyamorous relationships are built on the consent and knowledge of everyone involved."},
    ],
  },
};
